version: "3.7"

services:
  web:
    build:
      args:
        user: dev1
        uid: ${USER_ID}
      context:
        docker/web
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./web/:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:1.19.1-alpine
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./web/:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel

  composer:
    image: composer:latest
    volumes:
      - ./web/:/app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge